### ISSUE TITLE
Compatible with DIYLESS ESP8266 Thermostat Shield?

### ISSUE THREAD

**Issue by theelog** [Laxilef/OTGateway#1]
Is this compatible with DIYLESS ESP8266 Thermostat Shield?

https://diyless.com/product/esp8266-thermostat-shield

**Comment by Laxilef** [comment]
Yes
In settings set "Opentherm pin IN" = 4, "Opentherm pin OUT" = 5 for esp8266

**Comment by theelog** [comment]
Worked perfectly!

**Comment by Laxilef** [comment]
Great. Which boiler do you have? I'll add it to the compatibility list

**Comment by theelog** [comment]
I've got a Remeha Calenta Ace 40C.
