### ISSUE TITLE
Лимит температуры

### ISSUE THREAD

**Issue by RYZHOP** [Laxilef/OTGateway#102]
Установил настройки отопления мин. 20 макс. 80
ГВС мин.30 макс. 50

Но котел греет больше этих значений. И лимиты показывает он больше.

Vendor:          Viessmann
Member ID:       33
Flags:           81
Type:            100
Version:         30
OT version:      3
Heating limits:  20...80 °C
DHW limits:      30...60 °C

**Comment by Laxilef** [comment]
У котла есть свои лимиты и свой гистерезис, которые нельзя изменить через opentherm. Иногда эти значения можно поменять через сервисное меню котла, изучите документацию к котлу.
