### ISSUE TITLE
No MQTT connection after upgrade to 1.5

### ISSUE THREAD

**Issue by Pajuris** [Laxilef/OTGateway#103]
Strange, but I can not connect to Home assistant Mosquitto broker after update.
After few restarts (HA and OTGateway), opentherm gateway had appeared in HA. But after next OTGateway restart no connection again.
Connection to web interface is working good.

**Comment by Laxilef** [comment]
Hi,
Please upload logs

**Comment by Pajuris** [comment]
From where?

**Comment by Pajuris** [comment]
Solution: need check MQTT enable in Settings. :)
![mqtt](https://github.com/user-attachments/assets/4d84f7a4-5f66-4a94-b9b8-865a6b5455c7)
Sorry...

**Comment by Laxilef** [comment]
> * The names of some settings have been changed in this version. Not all settings will be restored from backup! Check them after restoration.
> * Sensor settings will not be restored automatically; they must be configured again on the Sensors settings page.
> * Very recommended to delete the device in Home Assistant before upgrading to avoid errors in the HA logs (due to the deletion of some entities)

**Comment by Pajuris** [comment]
Thanks, Laxilef...
O have one more question. No switches turn on/off heeating and DHW in Home Assistant after update? Removed or I need to reenable its?

**Comment by Laxilef** [comment]
Some entities have been removed or renamed. It is better to remove the device and add it again so that only working ones remain. To control heating and DHW, you must use the "climate" entities.

**Comment by Pajuris** [comment]
OK. Thanks, Laxilef.
