### ISSUE TITLE
Modulation level doesnt work after upgrade

### ISSUE THREAD

**Issue by shaggee** [Laxilef/OTGateway#106]
Today I upgraded D1 Mini ESP 32 from 1.4.0 to 1.5.0 and modulation level stays always 0% even boiler flame is on ant its heating.
Any advice to fix it?

![obraz](https://github.com/user-attachments/assets/f7f8bba9-c558-46a8-9d6f-90a0517e9329)

**Comment by Laxilef** [comment]
Hi,

Pls upload logs

**Comment by shaggee** [comment]
> Hi,
> 
> Pls upload logs

[logs.txt](https://github.com/user-attachments/files/18074718/logs.txt)

I found more missing diagnostic info which were visible in 1.4.0:
Boiler DHW max temp
Boiler DHW min temp
Boiler heating max te
Boiler heating min te
Diagnostic code
Modulation level

**Comment by Laxilef** [comment]
> Boiler DHW max temp
> Boiler DHW min temp
> Boiler heating max te
> Boiler heating min te

```
[09:07:33][OT][DHW][NOTICE] Received min temp: 35 (converted: 35), max temp: 65 (converted: 65)
[09:07:33][OT][HEATING][NOTICE] Received min temp: 25 (converted: 25), max temp: 48 (converted: 48)
```

> Modulation level

```
[09:08:10][OT][NOTICE] Received modulation level: 38%, power: 14.46 of 25.00 kW (min: 8.00 kW)
```

> Diagnostic code

Not polled if fault/diag state is inactive

---

I see no problems in the logs.
