### ISSUE TITLE
Tuning regulator PID

### ISSUE THREAD

**Issue by andrey150960** [Laxilef/OTGateway#108]
Здравствуйте, решил заморочиться с настройкой PID.
На сколько я понял OpenTherm Gateway PID min temp и OpenTherm Gateway PID max temp - это 
температурный диапазон нагрева котла. Это так ?
При нажатии OpenTherm Gateway Tuning ни чего не происходит. 
Т.е. автоматически коэффициенты не настраиваются.

**Comment by Laxilef** [comment]
Здравствуйте,

Pid тюнер был давно вырезан из прошивки, т.к. нормально не работал и на версии 1.5.0 его нет. Коэффициенты подбираются вручную.

Минимальная и максимальная температура для Pid относится только к Pid, глобальное ограничение в секции Heating/отопление.

**Comment by andrey150960** [comment]
Т.е если правильно понял "температура для Pid " это диапазон нагрева теплоносителя для PID.
Прошил на 1.5.0 , некоторые данные не отражаются в НА.
![Снимок](https://github.com/user-attachments/assets/1305922b-ebb9-4636-ba08-84516568ebf1)

**Comment by Laxilef** [comment]
> Very recommended to delete the device in Home Assistant before upgrading to avoid errors in the HA logs (due to the deletion of some entities)

**Comment by andrey150960** [comment]
Понял спасибо. Можно закрывать.

**Comment by andrey150960** [comment]
Понял спасибо
