### ISSUE TITLE
Добавить округление значений в сенсоры

### ISSUE THREAD

**Issue by upais** [Laxilef/OTGateway#112]
Приветствую.
Переработка настройки сенсоров отличная и удобная. Предлагаю добавить еще и округление значений после запятой. Значение той же температуры в виде 0.13 градусов не особо имеет смысл в такой точности, особенно с учетом погрешности измерений сами датчиков.

**Comment by Laxilef** [comment]
Здравствуйте.
Значения округляются до 2 знаков после запятой, потому что просили в чате для сбора статистики. В home assistant можете выбрать округление до целого числа в настройках сущности.

**Comment by upais** [comment]
1) Кому нужна статистика могли бы округлять до нужного им.
2) Home Assistant не обязательное ПО и не единственный УД.
3) В Home Assistant округление не работает в кастомных касточках, если в них нет такой поддержки. Либо шаблоны.
Тогда уж и коррекцию с фильтрацией можно было на HA переложить.

Ладно, дело автора.

**Comment by Laxilef** [comment]
> Кому нужна статистика могли бы округлять до нужного им.

Если мы округлим в прошивке, то потом разокруглить значение не получится)

> Home Assistant не обязательное ПО и не единственный УД.

Это верно, поэтому сделано универсально. Если в другой системе УД есть возможность округления, то там это тоже можно сделать.

> В Home Assistant округление не работает в кастомных касточках, если в них нет такой поддержки.

В т.ч. в кастомных карточках же просто отображается значение сущности, если в настройках сущности поменять округление, то там оно не применяется?
![изображение](https://github.com/user-attachments/assets/5e12344a-934b-49f1-9a1f-e27fc5311e60)

**Comment by upais** [comment]
> В т.ч. в кастомных карточках же просто отображается значение сущности, если в настройках сущности поменять округление, то там оно не применяется?

Как понимаю, HA не округляет значение до формирования самого сенсора, а делает это уже после и отображает в карточках. Но значение самого сенсора не меняется.
Вот пример. В панели разработчика тоже без округления.
![Снимок экрана 2024-12-27 182059](https://github.com/user-attachments/assets/058d679f-077b-4b3a-8392-4c57ea7bf93a)

Да, я понимаю, что сама доработка не имеет большой ценности, но она логично вписывается и если не трудозатратна, то почему бы и нет.
