### ISSUE TITLE
Request: Send MSG ID24 Room Temperature and ID27 Outside Temperature

### ISSUE THREAD

**Issue by aurelmarius** [Laxilef/OTGateway#14]
Hello,
Do you think is possible to send Room Temperature and Outside Temperature from HA to opentherm ? I'm running nodoshop's opentherm gateway in conjuction with your OTGateway and it supports ID24 and 27 from master device.
Also MsgID 57 Max CH water Setpoint that i set in OTGateway it is not sent to boiler, i had to set it manualy.
Thanks.
![otg](https://github.com/Laxilef/OTGateway/assets/7074653/ca63b85f-7127-4b0e-8a14-25d0cc89286d)

**Comment by Laxilef** [comment]
Hi,
Yes, ID 23 and 24 can be sent. But why is this necessary?
![Screenshot_7](https://github.com/Laxilef/OTGateway/assets/34578544/e9cec135-25fa-470d-a1bc-b4e1f94d85a1)

ID57 must be sent:
https://github.com/Laxilef/OTGateway/blob/ead8c64e925812ef27b3dc7517a04b07b2e89b5b/src/OpenThermTask.h#L216

**Comment by Laxilef** [comment]
I think this can be added.
P.S. What kind of display?

**Comment by aurelmarius** [comment]
It is a waveshare epaper 7.5 screen hooked up to esp32.
If it is too hard to implement this, i will eventualy flash the screen with esphome and get sensor data from homeassistant.
