### ISSUE TITLE
Adapter compatibility ESP32 S3 + DIYLESS

### ISSUE THREAD

**Issue by critictidier** [Laxilef/OTGateway#15]
Great project, thank you!

I’m currently using https://diyless.com/product/opentherm-thermostat2 based on ESP32 S3 and original firmware.

Please advise if I can use your latest release in that setup? I wouldn’t expect the display of that board to be compatible and it’s not important in my scenario.

**Comment by Laxilef** [comment]
Hi, thanks!
Now I'm working on stability on the esp32 platform. It should work on S3 too, but I haven't tested it. When the next version comes out, you can test it. But the display and BLE sensors are not supported.

For tests, you need to find out which GPIOs are connected to opentherm.
