### ISSUE TITLE
Report temperature from forecast doesn't work

### ISSUE THREAD

**Issue by SimplyKot** [Laxilef/OTGateway#16]
Use this instruction:
https://github.com/Laxilef/OTGateway/wiki#reporting-outdoor-temperature-from-home-assistant-weather-integration

On saving integration get error:
"Message malformed: Entity {{ source_entity }} is neither a valid entity ID nor a valid UUID for dictionary value @ data['entity_id'"

Attributes is present:
![изображение](https://github.com/Laxilef/OTGateway/assets/31762481/e6962e98-8150-4285-9b7c-a35968234381)

Делаю по инструкции и после копирования и редактирования скрипта автоматизации получаю ошибку:
"Message malformed: Entity {{ source_entity }} is neither a valid entity ID nor a valid UUID for dictionary value @ data['entity_id'"

При этом атрибуты в объекте weather.home есть.

Версия HA core 2023.2.2

telegram: @simply_kot

**Comment by Laxilef** [comment]
Обновил

**Comment by SimplyKot** [comment]
Сохранился нормально. 
При ручном запуске срабатывает норамльно, но при автоматическом запуске не выполнятеся.
Спотыкается о 
`condition:
  - condition: template
    value_template: "{{ has_value(source_entity) and has_value(target_entity) }}"`

С формулировкой 
Error: In 'template' condition: UndefinedError: 'has_value' is undefined

Трассировка:
![изображение](https://github.com/Laxilef/OTGateway/assets/31762481/451bdb6b-dd45-4050-a631-9c4c491c642c)

**Comment by Laxilef** [comment]
Какая версия HA? Функция has_value появилась с 2023.4

**Comment by SimplyKot** [comment]
Версия HA core 2023.2.2
На праздниках обновлюсь. Спасибо.

**Comment by Laxilef** [comment]
has_value можно заменить временно на 
```
source_entity not in ['0', 'unavailable']
```
Аналогично в других участках кода.

**Comment by Laxilef** [comment]
обновил, вернул совместимость с предыдущими версиями HA
