### ISSUE TITLE
In some conditions OTGateway reports 0 for setpoint and outdoor temperature

### ISSUE THREAD

**Issue by SimplyKot** [Laxilef/OTGateway#18]
In some conditions OTGateway reports 0 for setpoint and outdoor temperature

При некоторых условиях с контроллера проходят нули в параметрах "Установленная темпервтура" и  "Вненшяя температура".
![изображение](https://github.com/Laxilef/OTGateway/assets/31762481/2ada8b4d-8ea0-4a51-b099-d13eb6029e06)

**Comment by SimplyKot** [comment]
Прошивка 1.3.3
Данные о внешней темературе переправлены с gismeteo
Ошибка наблюдается при первом вклбчении шлюза.

Кроме того, есть проблема в определении досупности шлюза.

При потери wifi переходит в аварийный режим с предустановленной температурой (что просто отлично), но  в HA остается активным.
![изображение](https://github.com/Laxilef/OTGateway/assets/31762481/1015a0a4-5d33-4fb2-a721-5895dfd1b24d)
Тут в 15-00 отлючен роутер.

При этом термостат отображается активным и показывает постоянный нагрев.
![изображение](https://github.com/Laxilef/OTGateway/assets/31762481/c7af4277-9aa9-460c-8ffe-1e7074261ad8)

**Comment by SimplyKot** [comment]
Провел тестирование на отсутствие связи и на отсутствие питания
![изображение](https://github.com/Laxilef/OTGateway/assets/31762481/f1faad55-268c-474b-b06b-6209854c122b)

Вывод - OpenTherm Status - всегда выдает ОК, хотя Status определяет состояние правильно.

**Comment by Laxilef** [comment]
Спасибо! Поправлю.

**Comment by Laxilef** [comment]
Исправлено в мастер ветке, проверьте.
