### ISSUE TITLE
Opentherm Gateway Heating

### ISSUE THREAD

**Issue by strk90** [Laxilef/OTGateway#20]
Подскажите как установить на термостате Heating  целевую температуру 23,0 °C?
На термостате можно установить минимальную температуру 35°C.
Термостат контролирует температуру теплоносителя (heating temperature),  а не температуру в доме (indoor)?
  
(https://github.com/Laxilef/OTGateway/assets/119970190/9fda951b-f219-4945-a931-cf3f69fa9acc)

**Comment by Laxilef** [comment]
Как и любой другой термостат, он регулирует температуру теплоносителя. Для расчета температуры теплоносителя для поддержки желаемой температуры в доме используется ПЗА (погодозависимое регулирование, equitherm) или PID.
Если ни один из этих режимов не включен, то температуру теплоносителя нужно устанавливать самостоятельно.
Почитайте quick start в wiki.

**Comment by strk90** [comment]
Поскажите как задать желаемую температуру в доме? 
Нужно какой-то дополнительный термостат написать?

**Comment by Laxilef** [comment]
Включить и настроить Equitherm, настроить датчики внешней и внутренней температуры и установить желаемую температуру в термостате в home assistant.
![Screenshot_3](https://github.com/Laxilef/OTGateway/assets/34578544/48d8e64e-26c9-4a30-adbe-0c3eb6d46bf3)

**Comment by strk90** [comment]
Все я так сделал. 
Почему-то у меня целевой параметр, который отвечает за желаемую температуру, устанавливает желаемую температуру теплоносителя. 
Может проблема в моем котле? 
Модель котла baltur tesis 24.



![upload_2023_12_10_00_26_31_095](https://github.com/Laxilef/OTGateway/assets/119970190/c37f2d86-e7d0-44da-9ab9-c178fa24e2e7)

**Comment by strk90** [comment]
> Включить и настроить Equitherm, настроить датчики внешней и внутренней температуры и установить желаемую температуру в термостате в home assistant. <img alt="" width="40%" src="https://private-user-images.githubusercontent.com/34578544/289313022-1869d4a7-a70f-4353-8d69-1201590aafad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTc4OTcsIm5iZiI6MTcwMjE1NzU5NywicGF0aCI6Ii8zNDU3ODU0NC8yODkzMTMwMjItMTg2OWQ0YTctYTcwZi00MzUzLThkNjktMTIwMTU5MGFhZmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIxMzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZjAyYzA4ZWM2ODk3MzRjZDY1YWU2YWYwMDMyZTMwNDgzMWI0ZjdmMDE5NTkyOTE4ZTM5YWZjYzdjZTk2YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IfTqsV36oxp0kGf-B2KlSo3gKqx5V_WLltm1GE5HE_M"> <img alt="" width="40%" src="https://private-user-images.githubusercontent.com/34578544/289312904-48d8e64e-26c9-4a30-adbe-0c3eb6d46bf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTc4OTcsIm5iZiI6MTcwMjE1NzU5NywicGF0aCI6Ii8zNDU3ODU0NC8yODkzMTI5MDQtNDhkOGU2NGUtMjZjOS00YTMwLWFkYmUtMGMzZWI2ZDQ2YmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIxMzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNWRkZTk4ZjBjNTc3MjgyMDM1NjI1NDFhMmY0OTc3Zjg3MWI2ZDFkMjkxNGZhMmU5N2Y4N2U1MDMzZTJiNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1A8wg61UIAH_H-fPD5nsp5Bl_bWizoUmp6prXtURr1I">

Буду разбираться.
Спасибо!

**Comment by Laxilef** [comment]
Странно, после включения Equitherm через некоторое время конфигурация термостата ``climate.opentherm_heating`` должна была обновиться, в т.ч. нижний и верхний предел устанавливаемых температур. Попробуйте esp перезагрузить.
Версия 1.3.3 прошита?

**Comment by strk90** [comment]
Да, версия 1.3.3.
Попробую прошить другую esp.

**Comment by Laxilef** [comment]
Это последняя стабильная версия, всё нормально.
Попробуйте esp перезагрузить. После перезагрузки вся конфигурация сущностей должна обновиться.

**Comment by strk90** [comment]
Заработало! 
Спасибо!
