### ISSUE TITLE
Master branch doesn't compile for ESP8266

### ISSUE THREAD

**Issue by aurelmarius** [Laxilef/OTGateway#24]
I'm trying to compile the master branch for esp8266 d1 mini but it is failing. Do you have any idea what i'm doing wrong ?

> Building in release mode
Compiling .pio/build/d1_mini/src/main.cpp.o
Generating LD script .pio/build/d1_mini/ld/local.eagle.app.v6.common.ld
Compiling .pio/build/d1_mini/libbfb/OpenTherm Library/OpenTherm.cpp.o
Compiling .pio/build/d1_mini/libe72/PubSubClient/PubSubClient.cpp.o
Compiling .pio/build/d1_mini/lib469/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pio/build/d1_mini/lib469/ESP8266WiFi/CertStoreBearSSL.cpp.o
Compiling .pio/build/d1_mini/lib469/ESP8266WiFi/ESP8266WiFi.cpp.o
Compiling .pio/build/d1_mini/lib469/ESP8266WiFi/ESP8266WiFiAP.cpp.o
Compiling .pio/build/d1_mini/lib469/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
src/main.cpp:16:6: error: #elif with no expression
 #elif
      ^
In file included from src/main.cpp:27:0:
src/MainTask.h:68:10: error: #elif with no expression
     #elif
          ^
.pio/libdeps/d1_mini/PubSubClient/src/PubSubClient.cpp: In member function 'boolean PubSubClient::publish_P(const char*, const uint8_t*, unsigned int, boolean)':
.pio/libdeps/d1_mini/PubSubClient/src/PubSubClient.cpp:523:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     return (rc == expectedLength);
                   ^
In file included from .pio/libdeps/d1_mini/ArduinoJson/src/ArduinoJson.hpp:33:0,
                 from .pio/libdeps/d1_mini/ArduinoJson/src/ArduinoJson.h:9,
                 from src/main.cpp:3:
.pio/libdeps/d1_mini/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp: In constructor 'ArduinoJson::V700PB2::JsonDocument::JsonDocument(ArduinoJson::V700PB2::JsonDocument&&)':
.pio/libdeps/d1_mini/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:33:51: error: no matching function for call to 'ArduinoJson::V700PB2::JsonDocument::JsonDocument()'
   JsonDocument(JsonDocument&& src) : JsonDocument() {
                     

<img width="1695" alt="Screenshot 2023-12-17 at 21 25 22" src="https://github.com/Laxilef/OTGateway/assets/7074653/0bfbdc77-e358-4f43-a1b5-d3dafc310a88">

**Comment by Laxilef** [comment]
Fixed. Thanks!

**Comment by aurelmarius** [comment]
Thanks a lot.
