### ISSUE TITLE
Heating max temp is not set

### ISSUE THREAD

**Issue by martinarva** [Laxilef/OTGateway#26]
Hi!

I have set the heating max temp to 45 degrees, as i have under floor heating and more is not recommenced.

<img width="312" alt="Screenshot 2023-12-22 at 10 10 44" src="https://github.com/Laxilef/OTGateway/assets/77044330/bcde9507-b8df-435a-ab86-0e3c356b7ae9">

But in the diagnostic section it's still 80 degrees
<img width="318" alt="Screenshot 2023-12-22 at 10 10 53" src="https://github.com/Laxilef/OTGateway/assets/77044330/eb639d4f-0abb-4025-b112-69730aa64da9">

Using the latest 1.4.0-rc.5

**Comment by Laxilef** [comment]
The "Current heating max temp" is the maximum temperature that can be set in the boiler.  Often the value of this parameter can be changed through the boiler service menu.

However, "Heating max temp" will be used when calculating the heating temperature. This is easy to test: set the temperature to 30 degrees with PID/Equitherm enabled and see what maximum temperature is set in the "Heating setpoint".

These 2 parameters are not related to each other.  Except that you cannot set "Heating max temp" greater than "Current heating max temp".
