### ISSUE TITLE
Wifi Watchdog

### ISSUE THREAD

**Issue by blitzu** [Laxilef/OTGateway#30]
Hello, is possible to implement an watchdog for wifi or maybe for mqtt connection? If it cant't connect to mqtt for some time the board should reboot.

**Comment by Laxilef** [comment]
Hi. What for? The board will connect automatically when possible.
In addition, this will disrupt the emergency mode.

**Comment by blitzu** [comment]
Because is second time when my device get offline. It doesn't connect back even if restarted my wifi router. The signal is high. The device reconnected after power cycle

**Comment by Laxilef** [comment]
Version 1.3.3?

**Comment by blitzu** [comment]
V 1.4.0-rc 5

**Comment by Laxilef** [comment]
Can you test this on version 1.4.0-rc.9?

**Comment by aurelmarius** [comment]
> Can you test this on version 1.4.0-rc.9?

Compiled 1.4.0-rc.9, can't connect to wifi hotspot anymore. I had to manually reflash esp with older version.
![Uploading Screenshot 2024-01-13 at 10.51.50.png…]()

**Comment by Laxilef** [comment]
Oh, I forgot to say that starting from version rc9 it is necessary to flash the file system via platformio.

**Comment by aurelmarius** [comment]
> Oh, I forgot to say that starting from version rc9 it is necessary to flash the file system via platformio.

There is separate file for fs or flash just bin via platformio ?

**Comment by Laxilef** [comment]
![Screenshot_1](https://github.com/Laxilef/OTGateway/assets/34578544/56f07964-4375-4cf5-8538-fccb2dd30516)

**Comment by aurelmarius** [comment]
> ![Screenshot_1](https://github.com/Laxilef/OTGateway/assets/34578544/56f07964-4375-4cf5-8538-fccb2dd30516)
> 
> 

Future versions after 1.4.0-rc.9 will support ota ?

**Comment by Laxilef** [comment]
Yes. There is already an "Upgrade" page there.

**Comment by aurelmarius** [comment]
![image](https://github.com/Laxilef/OTGateway/assets/7074653/2eee0df5-b04e-40c6-8cec-c79ca795e6f8)
Up and running. Thanks for the info.

**Comment by aurelmarius** [comment]
After 4 hours it became unavailable and boiler reported F95 error (no ot connection). Running on d1_mini. Moved back to rc5 for now. I also noticed i get random reboots with rc5 but not hang ups.
![image](https://github.com/Laxilef/OTGateway/assets/7074653/d47586f0-a04e-4d60-bb24-aae3dec3aa90)

**Comment by aurelmarius** [comment]
> Can you save the logs on the latest version and upload them here? I'm interested in what happens at the moment of freezing and after.

Sure, but i don’t know how to get the logs.

**Comment by Laxilef** [comment]
You need to connect the ESP to your computer via USB, connect to the port using a serial client and configure recording to a file.
![Screenshot_2](https://github.com/Laxilef/OTGateway/assets/34578544/2722c6ee-271a-4545-807d-a99d3b51f4a4)

**Comment by Laxilef** [comment]
I also noticed that some users have similar problems when using DHCP. Can you try using a static ip for your esp?
