### ISSUE TITLE
Opentherm gateway Homeassistant parametars

### ISSUE THREAD

**Issue by DeadlySin2** [Laxilef/OTGateway#34]
It is not a bug, but i can't understant some parametrs in HomeAssistant:

1. Emergency target tempetature - as i anderstand it is a temperature when the boilel starts heating if the Use Emergency slider is on?
Like Frost Protection mode in Baxi???
2. Turning slader - What this function is suppose to do?
3. Turning regulator - What this function is suppose to do?
4. Use equitherm in emergency - What this function is suppose to do?

**Comment by Laxilef** [comment]
> Emergency mode. If the Wi-Fi connection is lost or the gateway cannot connect to the MQTT server, the mode will turn on. This mode will automatically maintain the set temperature and prevent your home from freezing. In this mode it is also possible to use equithermal curves (weather-compensated control).
