### ISSUE TITLE
navien NCB700 конденсатный

### ISSUE THREAD

**Issue by PavelTelnov** [Laxilef/OTGateway#36]
Спасибо за проделанную работу.
Собрал плату, прошил, подключил к котлу, подключил к HA. Наблюдаю работу в Grafana.
 Данные которые получаю с котла в приложении.
![Скриншот от 2024-01-31 22-00-16](https://github.com/Laxilef/OTGateway/assets/78699289/d257762f-b4ee-44e2-9f5a-ac09641170f6)
Котел регулирует температуру по обратке.
Панель Opentherm Gateway Heating - при изменении настроек температуры, на дисплее котла ничего  не меняется.
Панель Opentherm Gateway DHW - при изменении настроек температуры, на дисплее котла ничего  не меняется.
Так и должно быть?
Задача: управлять температурой горячей воды через HA. Стоит планшет в ванной, для себя хочу налить погорячее, для детей похолоднее. Не хочется бегать в котельную.
Вопрос 2: отображение температуры обратки можно реализовать?

**Comment by Laxilef** [comment]
> Так и должно быть?

Скорее всего да. Если температура ГВС и отопления меняется согласно установленным в HA. При подключении термостатов по opentherm через панель, как правило, нельзя менять температуру, только зайти в сервисный режим.

> Вопрос 2: отображение температуры обратки можно реализовать?

Еще не встречал, чтобы хоть один котел эту температуру возвращал по OT. Поэтому еще на первых версиях удалил этот параметр для опроса.
