### ISSUE TITLE
Can't get the correct values ​​for the Heating temp and setpoint

### ISSUE THREAD

**Issue by vespadrift** [Laxilef/OTGateway#41]
Good evening everyone, 
I can't get the correct values ​​for the Heating temperature and setpoint. I try to change the Master MemberID code without result...
I have a Radiant r2k and i use the esp8266 with the OpenTherm Adapter by https://github.com/ihormelnyk
![83258991-8756-4456-BEE9-A483501303D1_4_5005_c](https://github.com/Laxilef/OTGateway/assets/153445840/3e8ff0db-ac1d-41c1-805c-204eba47ae1d)

And on home assistant I can't adjust the temperature under 30°...but the value can be set between 30 and 80°
<img width="373" alt="Schermata 2024-02-08 alle 01 26 46" src="https://github.com/Laxilef/OTGateway/assets/153445840/3bac94b4-0a54-4f1c-83b2-3514d6a243de">
Any solution? thanks

**Comment by Laxilef** [comment]
If you are not using PID or equitherm mode, then everything is correct. In your case, you can set the temperature from 30 to 80 degrees.

**Comment by vespadrift** [comment]
Thank you so much! It works!
