### ISSUE TITLE
noob request

### ISSUE THREAD

**Issue by vespadrift** [Laxilef/OTGateway#45]
I can't set the indoor temperature with mqtt. I paste the report_temp_to_controller.yaml in config file like this, but doesn't work:
<img width="438" alt="Schermata 2024-02-09 alle 18 36 31" src="https://github.com/Laxilef/OTGateway/assets/153445840/c719c43c-2e52-450e-bc32-d633863f50de">
thanks

**Comment by blitzu** [comment]
Content of https://github.com/Laxilef/OTGateway/blob/master/assets/ha/report_temp_to_controller.yaml you have to create an automation with it
