### ISSUE TITLE
DHW temperature high when the DHW is not running 

### ISSUE THREAD

**Issue by vespadrift** [Laxilef/OTGateway#46]
The DHW temperature is often high when I’m not using the hot water:
![IMG_1079](https://github.com/Laxilef/OTGateway/assets/153445840/ac5dc4bc-cf30-4575-8c2a-092e8fa9c896)

Thank you

**Comment by Laxilef** [comment]
It's normal. Probably the DHW sensor is located somewhere near the heat exchanger.
