### ISSUE TITLE
Работа в режиме PID 

### ISSUE THREAD

**Issue by bigbrother72** [Laxilef/OTGateway#5]
Если включен PID режим, то температура вычисляется, только когда котел набирает температуру
Функция getPidTemp() вызывается только в одну сторону.
```

    if (settings.pid.enable && vars.states.heating) {
      float pidResult = getPidTemp(....
 
```
По достижении температуры, котел просто отключается, и setpoint далее не меняется.

Потом когда температура в помещении упадет меньше заданной, то котел  опять включается и начинает работать с предыдущей температуры - т.е .просто дискретный термостат on/off

И это еще не всё. После нескольких циклов что-то зависает и далее просто не включается отопление.

Установлено 21 градусов целевая температура. 
Сегодня утром проснулся. Дома холодно - 20.4 градусов,

Перезагрузил openterm  контроллер около 10 утра

В течении дня несколько раз набирало эту температур.
Сейчас до +20,8 уже упало. 
Через telnet вижу, что 
[INFO] Heating enabled: 1

Но отопление не включается

Все видно на графиках

![Screenshot 2023-10-10 at 20-55-46 Обзор – Home Assistant](https://github.com/Laxilef/OTGateway/assets/79911112/4f2b6d6a-acf6-4bd5-a233-ec693f02913d)
![Screenshot 2023-10-10 at 20-55-26 Обзор – Home Assistant](https://github.com/Laxilef/OTGateway/assets/79911112/bd2479e5-bdb9-4b27-9cff-d59658c49ff1)
![Screenshot 2023-10-10 at 20-52-39 Обзор – Home Assistant](https://github.com/Laxilef/OTGateway/assets/79911112/45002ed5-ee92-48e7-bb2f-882f52fc4913)

Скорее всего в коде openthermtask.h не работает ветка, так как heatingSetpoint  постоянно один и тот же

    // Температура отопления
    if (heatingEnable && fabs(vars.parameters.heatingSetpoint - currentHeatingTemp) > 0.0001) {
      INFO_F("Setting heating temp = %u \n", vars.parameters.heatingSetpoint);

      // Записываем заданную температуру
      if (ot->setBoilerTemperature(vars.parameters.heatingSetpoint)) {
        currentHeatingTemp = vars.parameters.heatingSetpoint;

      } else {
        WARN("Failed set heating temp");
      }
    }

После того как я поменял через температуру с +75 обогрева на 72 градуса, то сработала эта ветка и в телнете увидел:
[INFO] Setting heating temp = 72
[INFO] Heating enabled: 1

и обогрев начался.

**Comment by Laxilef** [comment]
Какой у вас котёл? Какое значение параметра hysteresis?
Предполагается, что vars.states.heating должен быть true даже если горелка котла выключена.

**Comment by Laxilef** [comment]
Проверьте

https://github.com/Laxilef/OTGateway/releases/tag/1.3.1

**Comment by bigbrother72** [comment]
> Какой у вас котёл? Какое значение параметра hysteresis? Предполагается, что vars.states.heating должен быть true даже если горелка котла выключена.

Котел Baxi Luna 3.
hysteresis =0.1


Еще вопрос:

В нижеуказанном коде наверное надо поменять лимиты 0-100 на vars.parameters.heatingMinTemp, vars.parameters.heatingMaxTemp, так как котел не может выдавать от 0 до 100 градусов температуру отопления.
```
    newTemp = round(newTemp);
    newTemp = constrain(newTemp, 0, 100);
    return newTemp;
```

**Comment by bigbrother72** [comment]
> Проверьте. Должно быть исправлено. После обновления настройки сбросятся на дефолтные, сохраните их перед обновлением, чтобы потом заново выставить.
> 
> https://github.com/Laxilef/OTGateway/releases/tag/1.3.1

завтра попробую.

**Comment by Laxilef** [comment]
> В нижеуказанном коде наверное надо поменять лимиты 0-100 на vars.parameters.heatingMinTemp, vars.parameters.heatingMaxTemp, так как котел не может выдавать от 0 до 100 градусов температуру отопления.

Там несколько лимитов дальше идет, последний:
https://github.com/Laxilef/OTGateway/blob/6d3172b73b2033a36a3b7c643ee0d3380d3fc5f4/src/RegulatorTask.h#L62C1-L64C6

**Comment by Symon84** [comment]
Hello, in my case I have both the PID and EQUITHERM active.. 
The hysteresis value is set to 0.5.I note that the PID calculates the value with respect to the setpoint temperature, i.e.: 20.5 degrees. Therefore, when the ambient temperature drops to 20.4 degrees, the PID increases the supply setpoint, but the boiler still has to start because it will start at 20 degrees. 
As a result, every time the boiler turns on at 20 degrees, the flow temperature setpoint is always at maximum (PID + EQUITHERM), and then gradually lowers as the ambient temperature rises. 
Is it possible to synchronize the PID with the boiler start-up? 
Or with the desired room temperature setpoint - the hysteresis value? 
It would be great if this thing could be enabled with a flag like "PID hysteresis sync"

**Comment by Laxilef** [comment]
Hi @Symon84 
Can you show the graph of ``sensor.opentherm_heating_temp``, ``sensor.opentherm_heating_setpoint_temp`` and ``binary_sensor.opentherm_flame``?

**Comment by Symon84** [comment]
> Hi [@Symon84](https://github.com/Symon84) Can you show the graph of `sensor.opentherm_heating_temp`, `sensor.opentherm_heating_setpoint_temp` and `binary_sensor.opentherm_flame`?

Yes:

![Image](https://github.com/user-attachments/assets/2d750a5b-680a-4c4b-a3ff-4ed05e401e01)

and this is a detail with indoor temp:

![Image](https://github.com/user-attachments/assets/25fbab7b-7217-4433-b850-84d45db8e076)
