### ISSUE TITLE
Outdoor and Indoor temp MQTT does not work properly

### ISSUE THREAD

**Issue by shaggee** [Laxilef/OTGateway#52]
Im using 1.4.0-rc.15 and when HomeAssistant reports indoor or outdoor temp via MQTT, its always changing back to 0 after few seconds.
Outdoor and indoor settings is switched to manual.

![obraz](https://github.com/Laxilef/OTGateway/assets/6645212/595fc779-c061-4ce0-b6e0-d3034c829fd3)

**Comment by Laxilef** [comment]
Pls try [rc16](https://github.com/Laxilef/OTGateway/releases/tag/1.4.0-rc.16)

**Comment by shaggee** [comment]
rc16 fixed problem
