### ISSUE TITLE
Проблемы с настройками. 

### ISSUE THREAD

**Issue by Balaganoff** [Laxilef/OTGateway#6]
С моим котлом AEG GBA124 прошивка не работает. Хотя другие (тасмота+опентерм и пр.) видят мой котел и регулируют. 
Тут использована какая-то урезанная библиотека ?

Вот ниже прилагаю лог из работающей Tasmota+opentherm

16:10:29.055 MQT: Подписаться на cmnd/tasmota_FD7A71/#
16:10:29.056 MQT: Подписаться на cmnd/tasmotas/#
16:10:29.058 MQT: Подписаться на cmnd/DVES_FD7A71_fb/#
16:10:29.061 MQT: tele/tasmota_FD7A71/INFO1 = {"Info1":{"Module":"Generic","Version":"13.1.0(TasmoCompiler-esp82664M)","FallbackTopic":"cmnd/DVES_FD7A71_fb/","GroupTopic":"cmnd/tasmotas/"}}
16:10:29.070 MQT: tele/tasmota_FD7A71/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"tasmota-FD7A71-6769","IPAddress":"192.168.1.4"}}
16:10:29.084 MQT: tele/tasmota_FD7A71/INFO3 = {"Info3":{"RestartReason":"Software/System restart","BootCount":5}}
16:10:29.096 TFS: File 'autoexec.bat' not found
16:10:29.222 [OTH]: perform handshake
16:10:29.665 [OTH]: Processing response. Status=SUCCESS, Response=0xC0030129
16:10:29.666 [OTH]: getLastResponseStatus SUCCESS. Slave Cfg: C0030129
16:10:30.122 SRC: MQTT
16:10:30.124 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 1, Pld 1, Data '1'
16:10:30.130 MQT: stat/tasmota_FD7A71/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"","RestartReason":"Software/System restart","Uptime":"0T00:00:08","StartupUTC":"2023-10-13T15:10:22","Sleep":50,"CfgHolder":4617,"BootCount":4,"BCResetTime":"2023-10-13T15:52:54","SaveCount":14,"SaveAddress":"1000"}}
16:10:30.172 SRC: MQTT
16:10:30.175 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 2, Pld 11, Data '11'
16:10:30.181 MQT: stat/tasmota_FD7A71/STATUS11 = {"StatusSTS":{"Time":"2023-10-13T16:10:30","Uptime":"0T00:00:08","UptimeSec":8,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":28,"MqttCount":1,"Wifi":{"AP":1,"SSId":"MiHome","BSSId":"74:4D:28:BF:88:1C","Channel":11,"Mode":"11n","RSSI":54,"Signal":-73,"LinkCount":1,"Downtime":"0T00:00:05"}}}
16:10:30.316 QPC: Reset
16:10:30.351 [OTH]: Processing response. Status=SUCCESS, Response=0x40000200
16:10:30.354 SRC: MQTT
16:10:30.357 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 2, Pld 10, Data '10'
16:10:30.365 MQT: stat/tasmota_FD7A71/STATUS10 = {"StatusSNS":{"Time":"2023-10-13T16:10:30","DS18B20":{"Id":"00000215ECB7","Temperature":24.9},"OPENTHERM":{"conn":"READY","settings":3,"SLAVE":{"FAULT":0,"CH":0,"DHW":0,"FL":0,"COOL":0,"CH2":0,"DIAG":0,"RAW":1073742336}},"TempUnit":"C"}}
16:10:30.452 [OTH]: Setting Boiler Temp. Old: 0, New: 85, Force: N
16:10:30.903 [OTH]: Processing response. Status=SUCCESS, Response=0xD0015500
16:10:31.005 [OTH]: Setting Hot Water Temp. Old: 0, New: 36
16:10:31.489 [OTH]: Processing response. Status=SUCCESS, Response=0xD0382400
16:10:32.095 [OTH]: Processing response. Status=SUCCESS, Response=0xC0050000
16:10:32.195 APP: Количество загрузок 5
16:10:32.952 CFG: Сохранено во флэш-память 3FB, Подсчет 15, Байт 4096
16:10:32.959 [OTH]: Processing response. Status=INVALID, Response=0x70730000
16:10:33.165 MQT: tele/tasmota_FD7A71/STATE = {"Time":"2023-10-13T16:10:33","Uptime":"0T00:00:11","UptimeSec":11,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":55,"MqttCount":1,"Wifi":{"AP":1,"SSId":"MiHome","BSSId":"74:4D:28:BF:88:1C","Channel":11,"Mode":"11n","RSSI":58,"Signal":-71,"LinkCount":1,"Downtime":"0T00:00:05"}}
16:10:33.196 MQT: tele/tasmota_FD7A71/SENSOR = {"Time":"2023-10-13T16:10:33","DS18B20":{"Id":"00000215ECB7","Temperature":24.9},"OPENTHERM":{"conn":"BUSY","settings":3,"SLAVE":{"FAULT":0,"CH":0,"DHW":0,"FL":0,"COOL":0,"CH2":0,"DIAG":0,"RAW":1073742336},"BTMP":{"FAULT":0,"REQ":85.0,"ACT": 85.0},"HWTMP":{"REQ":36.0,"ACT": 36.0},"ASFF":{"FC":0,"OFC":0}},"TempUnit":"C"}
16:10:33.583 [OTH]: Processing response. Status=SUCCESS, Response=0xC0110000
16:10:33.640 HTP: Управление
16:10:34.135 [OTH]: Processing response. Status=SUCCESS, Response=0x40191800
16:10:34.736 [OTH]: Processing response. Status=SUCCESS, Response=0x401A1700
16:10:35.340 [OTH]: Processing response. Status=INVALID, Response=0x601B0000
16:10:35.748 HTP: Консоль
16:10:35.971 [OTH]: Processing response. Status=INVALID, Response=0x701C0000
16:10:36.521 [OTH]: Processing response. Status=SUCCESS, Response=0x40382400
16:10:37.126 [OTH]: Processing response. Status=SUCCESS, Response=0xC0390000
16:10:37.734 [OTH]: Processing response. Status=SUCCESS, Response=0xC00A0C00
16:10:38.204 MQT: tasmota/discovery/3C6105FD7A71/config = {"ip":"192.168.1.4","dn":"Tasmota","fn":["Tasmota",null,null,null,null,null,null,null],"hn":"tasmota-FD7A71-6769","mac":"3C6105FD7A71","md":"Generic","ty":0,"if":0,"ofln":"Offline","onln":"Online","state":["OFF","ON","TOGGLE","HOLD"],"sw":"13.1.0","t":"tasmota_FD7A71","ft":"%prefix%/%topic%/","tp":["cmnd","stat","tele"],"rl":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"swc":[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],"swn":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"btn":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"so":{"4":0,"11":0,"13":0,"17":0,"20":0,"30":0,"68":0,"73":0,"82":0,"114":0,"117":0},"lk":0,"lt_st":0,"bat":0,"dslp":0,"sho":[],"sht":[],"ver":1} (нераспред.)
16:10:38.218 MQT: tasmota/discovery/3C6105FD7A71/sensors = {"sn":{"Time":"2023-10-13T16:10:38","DS18B20":{"Id":"00000215ECB7","Temperature":24.9},"OPENTHERM":{"conn":"BUSY","settings":3,"SLAVE":{"FAULT":0,"CH":0,"DHW":0,"FL":0,"COOL":0,"CH2":0,"DIAG":0,"RAW":1073742336},"BTMP":{"FAULT":0,"REQ":85.0,"ACT": 85.0},"HWTMP":{"REQ":36.0,"ACT": 36.0},"ASFF":{"FC":0,"OFC":0},"FLM":0.0,"TB":24.0,"TDHW":23.0,"DHWS":36.0,"TMAX":0.0,"OT10":{"lo":0,"hi":0}},"TempUnit":"C"},"ver":1} (нераспред.)
16:10:38.336 [OTH]: Processing response. Status=INVALID, Response=0xF00C0000
16:10:38.942 [OTH]: Processing response. Status=INVALID, Response=0x700E0000
16:10:39.545 [OTH]: Processing response. Status=INVALID, Response=0xF00F0000
16:10:40.149 [OTH]: Processing response. Status=INVALID, Response=0xF0120000
16:10:40.753 [OTH]: Processing response. Status=INVALID, Response=0x70130000
16:10:41.359 [OTH]: Processing response. Status=INVALID, Response=0xF0210000
16:10:41.972 [OTH]: Processing response. Status=INVALID, Response=0xF0740000
16:10:42.533 [OTH]: Processing response. Status=INVALID, Response=0x70750000
16:10:43.139 [OTH]: Processing response. Status=INVALID, Response=0xF0780000
16:10:43.744 [OTH]: Processing response. Status=INVALID, Response=0x70790000
16:10:44.416 [OTH]: Processing response. Status=SUCCESS, Response=0x40000200
16:10:45.253 [OTH]: Processing response. Status=SUCCESS, Response=0xC0050000
16:10:45.864 [OTH]: Processing response. Status=INVALID, Response=0x70730000
16:10:46.415 [OTH]: Processing response. Status=SUCCESS, Response=0xC0110000
16:10:47.020 [OTH]: Processing response. Status=SUCCESS, Response=0x40191800
16:10:47.623 [OTH]: Processing response. Status=SUCCESS, Response=0xC01A1600
16:10:47.811 WIF: Проверка соединения...
16:10:48.227 [OTH]: Processing response. Status=INVALID, Response=0x601B0000
16:10:48.835 [OTH]: Processing response. Status=INVALID, Response=0x701C0000
16:10:49.423 [OTH]: Processing response. Status=SUCCESS, Response=0x40382400
16:10:50.054 [OTH]: Processing response. Status=SUCCESS, Response=0xC0390000

Я правильно понял - можно по-русски?

**Comment by Laxilef** [comment]
Опишите что не работает: не регулирует температуру, не получает значения с датчиков и т.д.
У тасмоты такая же библиотека от Игоря Мельника.
Пины правильные в настройках вписаны?

**Comment by Balaganoff** [comment]
Спасибо за ответ разобрался ! У меня пины не так распаяны (осталось от другого проекта) как на вашей схеме.
В настройках изменения не сохраняются. По крайней мере как я ни старался не получилось. Пришлось пересобрать из исходников по свои пины и котел ответил ! Я почти счастлив ! )) 
Еще один вопрос - как заставить работать 18b20 чтобы температуру внутри помещения учитывало именно с него ?
Датчик точно подключен правильно и работает. 
struct {
      // 1 - manual, 2 - ds18b20
      byte type = 2;
      byte pin = 12;
      float offset = 0.0f;
    } indoor;

Я даже попытался установить тип 2 , но это мне не помогло.
opentherm_indoor_temp можно регулировать только вручную, а хотелось-бы с подключенного датчика 
(так скоро освою программирование на старости лет :)))

**Comment by Laxilef** [comment]
После сборки из исходников настройки сохраняются?

**Comment by Balaganoff** [comment]
> После сборки из исходников настройки сохраняются?

Я не пробовал ( Я просто поправил в исходниках под свои пины и все заработало. 
Буду рядом еще раз попробую и доложу результат.  Ждем новых версий ! Спасибо за работу !

**Comment by Laxilef** [comment]
Выложил билды для разных esp8622: https://github.com/Laxilef/OTGateway/releases/tag/1.3.1
Возможно у вас wemos с 4мб памяти, а вы залили билд для wemos 16мб, поэтому и не сохраняются настройки :)
Попробуйте залить firmware_d1_mini.bin или, если не поможет, firmware_d1_mini_lite.bin 

Напишите потом пожалуйста по результатам.

**Comment by Balaganoff** [comment]
> Выложил билды для разных esp8266: https://github.com/Laxilef/OTGateway/releases/tag/1.3.1 Возможно у вас wemos с 4мб памяти, а вы залили билд для wemos 16мб, поэтому и не сохраняются настройки :) Попробуйте залить firmware_d1_mini.bin или, если не поможет, firmware_d1_mini_lite.bin
> 
> Напишите потом пожалуйста по результатам.

Да, у меня wemos d1 mini  с 4мб. Пока перезаписать прошивку нет возможности. 
А кроме несохранения настроек различия в объеме памяти еще на что-то влияет?

**Comment by Laxilef** [comment]
Нет, не влияет. Но сохранение настроек - весьма важная функция :)

**Comment by Laxilef** [comment]
По работе с котлом AEG GBA124 все нормально? Могу в список совместимых добавить?

**Comment by ananyevgv** [comment]
Baxi Nuvola-3 необходимо включить ch_2,  иначе горячая вода не работает

**Comment by Balaganoff** [comment]
> По работе с котлом AEG GBA124 все нормально? Могу в список совместимых добавить?

Да этот котел все отображает (кроме давления)  и реагирует корректно.

**Comment by Laxilef** [comment]
> Baxi Nuvola-3 необходимо включить ch_2, иначе горячая вода не работает

Он всегда включен:
```c++
    localResponse = ot->setBoilerStatus(
      heatingEnabled,
      settings.opentherm.dhwPresent && settings.dhw.enable,
      false, false, true/* <<< ch2 */, false, false
    );
```
