### ISSUE TITLE
how i install this integration in HomeAssistant

### ISSUE THREAD

**Issue by PrimitixLuke** [Laxilef/OTGateway#60]
Hi i have a problem with the installation of this integration in HA.
when by hacs i try to install the code he gives me this error: "<Integration Laxilef/OTGateway> Repository structure for 1.3.3 is not compliant"

How can i fix, i need this integration to connect the immergas thermostator.

I wait your response
Thanks

**Comment by Laxilef** [comment]
Hi, this is not an integration for HA :) This is firmware for ESP, which has integration with HA via MQTT Discovery.
