### ISSUE TITLE
Счетчик импульсов

### ISSUE THREAD

**Issue by andrey150960** [Laxilef/OTGateway#63]
Здравствуйте уважаемый.
Прошу вас если есть возможность добавить в прошивку "счетный вход"
К этому входу планирую  подключить геркон и считать импульсы с газового счетчика.
Т.е. имеем импульсы переводим в потребление газа.

**Comment by Laxilef** [comment]
Здравствуйте.
Я думаю с этим прекрасно справится и [pulse counter](https://esphome.io/components/sensor/pulse_counter) в esphome. Добавлять этот же функционал в прошивку для управления котлом не вижу смысла.

**Comment by andrey150960** [comment]
Да, согласен , но ставить вторую плату в эту же коробку как то не очень хочется. А так спасибо за вашу работу.
