### ISSUE TITLE
Just a question about ESP32 hardware

### ISSUE THREAD

**Issue by iz8mbw** [Laxilef/OTGateway#67]
Helllo.
I have just a question about hardware needed.
Why an ESP32 board cannot be directly connected using the GPIO PINs to the boiler?
So, if I connect the ESP32 board pins directly to the bolier it does not work?

Thanks!

**Comment by Laxilef** [comment]
Hi
On the openterm bus the voltage is higher than 3.3 volts (up to 48 volts), the ESP will break down.
