### ISSUE TITLE
OpenTherm Settings inputs rollback to default after refresh

### ISSUE THREAD

**Issue by Quiss** [Laxilef/OTGateway#76]
Hello @Laxilef, Thank you for the work, everything is just great.

I encountered a problem where after entering the settings - they are saved on the device, but reset in the settings panel to default values while other parameters remain unchanged. For example, in GPIO I use 7 / out 8, but after saving - I see 13 and 15 again, but the adjustment starts working!

This also applies to switches. It would be convenient to "modify" instead of entering again. Thank you!

Version: | 1.4.2
Env: nodemcu_8266
Date: Jun 15 2024 03:05:50
Core/SDK: 3.1.2

![image](https://github.com/Laxilef/OTGateway/assets/4972114/d9f3939d-6755-428c-a3ce-a47ec6f27efe)

**Comment by Laxilef** [comment]
Hi @Quiss, thanks!
GPIO 7 and 8 is not valid for nodemcu 8266, see pinout:
![ESP8266-NodeMCU-kit-12-E-pinout-gpio-pin](https://github.com/Laxilef/OTGateway/assets/34578544/59fcead3-dd45-46c6-b1c3-d62255a4b67e)

Most likely you meant D7 and D8, which are equal to GPIO 13 and 15?

**Comment by Quiss** [comment]
@Laxilef why? (I don't understand microcontrollers)

When specifying 7 8 everything works, but as I said above - it resets to the default value

 [SmartTherm](https://www.ozon.ru/product/kontroller-kotla-otopleniya-smarttherm-808382394/) usage 7 and 8
https://drive.google.com/file/d/1Wv_77LTP45Vh3wCga1CM9oiGG6yuRg94/view
![image](https://github.com/Laxilef/OTGateway/assets/4972114/410955d8-751a-441d-bab0-5ac668d0b6a8)

**Comment by Laxilef** [comment]
Hi @Quiss,

See pinout
D7 = GPIO13
D8 = GPIO15

**Comment by Quiss** [comment]
@Laxilef I'll have to learn this, Thanks!)
