### ISSUE TITLE
Boiler goes into fault mode when heating is off

### ISSUE THREAD

**Issue by mcmaier** [Laxilef/OTGateway#81]
> Please create an issue and upload logs.

Basically the interface seems to work: It reads out values and the burner goes on, when a temperature is set. But when heating is turned off, after a few minutes a fault occures: "External control not available".
Also not sure if settings are correct (master member ID?) Is there a possibility to get more info out of the attached log? Will provide more logs soon.
Thanks in advance.

[1m[00:05:37][22m[1m[OT][22m[1m[TRACE][22m[m ID:   56   Request: 90383700   Response: 60383700   Attempt:  1   Status: INVALID
[1m[00:05:37][22m[1m[OT][22m[1m[DHW][22m[1m[WARN][22m[m Failed set temp
[1m[00:05:38][22m[1m[MAIN][22m[1m[VERB][22m[m Free heap size: 24488 of 81920 bytes (min: 18976, diff: 0), max free block: 23584 (min: 16152, diff: 0, frag: 3%)
[1m[00:05:38][22m[1m[OT][22m[1m[TRACE][22m[m ID:    0   Request:      300   Response: c000030a   Attempt:  1   Status: SUCCESS
[1m[00:05:38][22m[1m[OT][22m[1m[TRACE][22m[m ID:   17   Request:   110000   Response: c0110c00   Attempt:  1   Status: SUCCESS
[1m[00:05:39][22m[1m[OT][22m[1m[TRACE][22m[m ID:   26   Request: 801a0000   Response: 401a363c   Attempt:  1   Status: SUCCESS
[1m[00:05:39][22m[1m[OT][22m[1m[TRACE][22m[m ID:   19   Request: 80130000   Response: e0130000   Attempt:  1   Status: INVALID
[1m[00:05:39][22m[1m[OT][22m[1m[TRACE][22m[m ID:   25   Request: 80190000   Response: c01925f0   Attempt:  1   Status: SUCCESS
[1m[00:05:39][22m[1m[OT][22m[1m[TRACE][22m[m ID:   28   Request: 801c0000   Response: 401c1cf4   Attempt:  1   Status: SUCCESS
[1m[00:05:39][22m[1m[SENSORS][22m[1m[INDOOR][22m[1m[TRACE][22m[m Raw temp: 19.875000
[1m[00:05:39][22m[1m[OT][22m[1m[TRACE][22m[m ID:   33   Request:   210000   Response: 60210000   Attempt:  1   Status: INVALID
[1m[00:05:39][22m[1m[OT][22m[1m[DHW][22m[1m[INFO][22m[m Set temp: 55.00 (converted: 55.00)
[1m[00:05:40][22m[1m[OT][22m[1m[TRACE][22m[m ID:   56   Request: 90383700   Response: 60383700   Attempt:  1   Status: INVALID
[1m[00:05:40][22m[1m[OT][22m[1m[DHW][22m[1m[WARN][22m[m Failed set temp
[1m[00:05:41][22m[1m[OT][22m[1m[TRACE][22m[m ID:    0   Request:      300   Response: c000030a   Attempt:  1   Status: SUCCESS
[1m[00:05:41][22m[1m[OT][22m[1m[TRACE][22m[m ID:   17   Request:   110000   Response: c0110c00   Attempt:  1   Status: SUCCESS
[1m[00:05:41][22m[1m[OT][22m[1m[TRACE][22m[m ID:   26   Request: 801a0000   Response: 401a363c   Attempt:  1   Status: SUCCESS
[1m[00:05:41][22m[1m[MQTT][22m[1m[TRACE][22m[m Successfully publish 6 of 6 bytes to topic: opentherm/status
[1m[00:05:41][22m[1m[OT][22m[1m[TRACE][22m[m ID:   19   Request: 80130000   Response: e0130000   Attempt:  1   Status: INVALID
[1m[00:05:42][22m[1m[OT][22m[1m[TRACE][22m[m ID:   25   Request: 80190000   Response: 40192788   Attempt:  1   Status: SUCCESS
[1m[00:05:42][22m[1m[MQTT][22m[1m[TRACE][22m[m Successfully publish 704 of 704 bytes to topic: opentherm/state
[1m[00:05:42][22m[1m[OT][22m[1m[TRACE][22m[m ID:   28   Request: 801c0000   Response: 401c1cd0   Attempt:  1   Status: SUCCESS
[1m[00:05:42][22m[1m[OT][22m[1m[TRACE][22m[m ID:   33   Request:   210000   Response: 60210000   Attempt:  1   Status: INVALID
[1m[00:05:42][22m[1m[OT][22m[1m[DHW][22m[1m[INFO][22m[m Set temp: 55.00 (converted: 55.00)
[1m[00:05:42][22m[1m[OT][22m[1m[TRACE][22m[m ID:   56   Request: 90383700   Response: 60383700   Attempt:  1   Status: INVALID
[1m[00:05:42][22m[1m[OT][22m[1m[DHW][22m[1m[WARN][22m[m Failed set temp
[1m[00:05:44][22m[1m[SENSORS][22m[1m[INDOOR][22m[1m[TRACE][22m[m Raw temp: 19.875000
[1m[00:05:44][22m[1m[OT][22m[1m[TRACE][22m[m ID:    0   Request:      300   Response:        0   Attempt:  1   Status: TIMEOUT
[1m[00:05:45][22m[1m[OT][22m[1m[TRACE][22m[m ID:    0   Request:      300   Response: c000030a   Attempt:  2   Status: SUCCESS
[1m[00:05:45][22m[1m[OT][22m[1m[TRACE][22m[m ID:   17   Request:   110000   Response: c0110c00   Attempt:  1   Status: SUCCESS
[1m[00:05:45][22m[1m[OT][22m[1m[TRACE][22m[m ID:   26   Request: 801a0000   Response: 401a363c   Attempt:  1   Status: SUCCESS
[1m[00:05:45][22m[1m[OT][22m[1m[TRACE][22m[m ID:   19   Request: 80130000   Response: e0130000   Attempt:  1   Status: INVALID
[1m[00:05:46][22m[1m[OT][22m[1m[TRACE][22m[m ID:   25   Request: 80190000   Response: c01929cc   Attempt:  1   Status: SUCCESS
[1m[00:05:46][22m[1m[OT][22m[1m[TRACE][22m[m ID:   28   Request: 801c0000   Response: c01c1cac   Attempt:  1   Status: SUCCESS
[1m[00:05:46][22m[1m[OT][22m[1m[TRACE][22m[m ID:   33   Request:   210000   Response: 60210000   Attempt:  1   Status: INVALID
[1m[00:05:46][22m[1m[OT][22m[1m[DHW][22m[1m[INFO][22m[m Set temp: 55.00 (converted: 55.00)
[1m[00:05:46][22m[1m[OT][22m[1m[TRACE][22m[m ID:   56   Request: 90383700   Response: 60383700   Attempt:  1   Status: INVALID
[1m[00:05:46][22m[1m[OT][22m[1m[DHW][22m[1m[WARN][22m[m Failed set temp
[1m[00:05:47][22m[1m[OT][22m[1m[TRACE][22m[m ID:    0   Request:      300   Response: c000030a   Attempt:  1   Status: SUCCESS
[1m[00:05:47][22m[1m[OT][22m[1m[TRACE][22m[m ID:   17   Request:   110000   Response: c0110c00   Attempt:  1   Status: SUCCESS
[1m[00:05:48][22m[1m[OT][22m[1m[TRACE][22m[m ID:   26   Request: 801a0000   Response: 401a363c   Attempt:  1   Status: SUCCESS
[1m[00:05:48][22m[1m[OT][22m[1m[TRACE][22m[m ID:   19   Request: 80130000   Response: e0130000   Attempt:  1   Status: INVALID
[1m[00:05:48][22m[1m[OT][22m[1m[TRACE][22m[m ID:   25   Request: 80190000   Response: c0192b20   Attempt:  1   Status: SUCCESS
[1m[00:05:48][22m[1m[OT][22m[1m[TRACE][22m[m ID:   28   Request: 801c0000   Response: c01c1cac   Attempt:  1   Status: SUCCESS
[1m[00:05:48][22m[1m[OT][22m[1m[TRACE][22m[m ID:   33   Request:   210000   Response: 60210000   Attempt:  1   Status: INVALID
[1m[00:05:48][22m[1m[OT][22m[1m[DHW][22m[1m[INFO][22m[m Set temp: 55.00 (converted: 55.00)
[1m[00:05:49][22m[1m[SETTINGS][22m[1m[INFO][22m[m Updated
[1m[00:05:49][22m[1m[OT][22m[1m[TRACE][22m[m ID:   56   Request: 90383700   Response: 60383700   Attempt:  1   Status: INVALID
[1m[00:05:49][22m[1m[OT][22m[1m[DHW][22m[1m[WARN][22m[m Failed set temp
[1m[00:05:49][22m[1m[SENSORS][22m[1m[INDOOR][22m[1m[TRACE][22m[m Raw temp: 19.875000

**Comment by Laxilef** [comment]
Hi,

Can you upload the logs showing the moment the error occurred?
The logs from the first message were written AFTER the error occurred, right?
