### ISSUE TITLE
HotSpot doesn't appear

### ISSUE THREAD

**Issue by maframan** [Laxilef/OTGateway#82]
I tried to flash with ESP Flash Download Tool three different esp board (esp8266 d1 mini, nodemcu esp32 s, nodemcu esp32 s3) but in all cases the hotspot doesn't appear. I followed the your guide (https://github.com/Laxilef/OTGateway/wiki#quick-start) and for each board I used the correct filesystem and image file.
For d1 mini: filesystem_d1_mini_1.4.4.bin and  firmware_d1_mini_1.4.4.bin
For nodemcu esp32-s and esp32s3: filesystem_nodemcu_32_1.4.4.bin and firmware_nodemcu_32_1.4.4.factory.bin

Below the ESP Flash tool screenshot:

![image](https://github.com/user-attachments/assets/c2015504-3afa-40cf-96d2-3c25e98b584f)

where am I going wrong?

**Comment by edems88** [comment]
I have the same thing.

**Comment by Laxilef** [comment]
Hi,

You are using the wrong addresses. The firmware file should be written to address 0x0, and the file system to the address as written in the manual:

ESP8266: 0x300000
ESP32: 0x370000

Not the other way around.

**Comment by maframan** [comment]
Thanks, You are right
