### ISSUE TITLE
Частые "Software reset due to exception/panic"

### ISSUE THREAD

**Issue by upais** [Laxilef/OTGateway#88]
Добрый день.
Начал замечать, что контроллер падает\ребутается каждые несколько часов. Раньше тоже было, но редко, может 1-2 в месяц.
Причина: Software reset due to exception/panic

Отладку включил, консолью подключился, но отловить довольно проблемно. Как-то еще можно диагностику провести?

![Снимок экрана 2024-10-29 083255](https://github.com/user-attachments/assets/f4ec0182-c85d-4f4f-b678-3b882426f421)
![Снимок экрана 2024-10-29 083354](https://github.com/user-attachments/assets/c8fb3d81-a852-4fc2-9b47-25fdf272921b)

**Comment by Laxilef** [comment]
Здравствуйте, попробуйте бету.
[build.zip](https://github.com/user-attachments/files/17562652/build.zip)

**Comment by upais** [comment]
Неа, тоже самое, причина только: Reset due to other watchdogs
До прошивки беты решил еще раз прошить 1.4.5, т.к. падать стал каждые 3-7мин. На Бете вроде реже, ночью даже 4 часа проработал. Настройки не менялись, после перепрошивки восстанавливал бэкап двухнедельной давности.
[debug (1).json](https://github.com/user-attachments/files/17566846/debug.1.json)
![Снимок экрана 2024-10-30 085936](https://github.com/user-attachments/assets/367c2a3b-cadb-4735-980d-e686875926e1)

**Comment by Laxilef** [comment]
Спасибо за логи. А какой датчик ble используете?

**Comment by upais** [comment]
LYWSD03MMC на прошивке pvvx.
С ним тоже ничего не менялось.

**Comment by Laxilef** [comment]
Ок, попозже выложу новый билд для тестов.

**Comment by upais** [comment]
Есть подозрения, что падает из-за взаимодействия с BLE датчиком?
Я недавно переключил на MQTT, пока не показатель, но вот 2 часа не падает. 

Кстати, а возможно, чтобы при старте контроллер опрашивал датчик и получал актуальную температуру? Либо хотя бы запоминал последнюю, если датчик невозможно принудительно опросить. А то основная проблема падений, это то что после старта контроллер считает, что на внутреннем датчике 0гр, а датчик может долго не передавать новые данные (у меня было более часа), то котел греет и греет.

**Comment by upais** [comment]
Да вроде должна быть нормальная связь, я его и перемещал ближе, там метров 4-5 через стену.
Попробую ему мощность увеличить, интереса ради.
А так, по mqtt уже более 5 часов.

**Comment by Laxilef** [comment]
Попробуйте с этим билдом
[build.zip](https://github.com/user-attachments/files/17580063/build.zip)

На качество связи с датчиком, однако, это не повлияет, только должно устранить краши.

**Comment by upais** [comment]
Предположительно, решилась проблема. Порядка 1,5 часов работало без падений, а в логах сообщения, что не удалось подключиться к BLE датчику. Я решил изменить ему мощность, она дефолтовая стояла и тоже не смог подключится, далее вынул батарейку и больше он с ней даже не включился. Похоже из-за низкого заряда датчик подглючивало. Хотя когда это началось датчик передавал данные примерно так же оперативно как и раньше.

**Comment by Laxilef** [comment]
> Порядка 1,5 часов работало без падений

Я так и не понял, вы последний билд прошили или нет?

**Comment by upais** [comment]
Конечно, это с ним 1,5 часа проработало. По этому и говорю, что скорей всего, проблема решена. Хоть 1,5 часа не много, но на предыдущих падало каждые 5-15мин.

**Comment by Laxilef** [comment]
Хорошо. Понаблюдайте еще, если все хорошо, то можете закрыть issue.

**Comment by upais** [comment]
Большое спасибо за оперативную помощь!
