### ISSUE TITLE
OTGateway keeps on crushing and rebooting on hardware watchdog (memory leakage?)

### ISSUE THREAD

**Issue by abratchik** [Laxilef/OTGateway#89]
Testing the latest release:

Version	1.4.5
Build	Env: nodemcu_8266
Date: Oct 13 2024 22:57:22
Core/SDK: 3.1.2
Uptime	0 days, 0 hours, 0 min., 29 sec.
Free memory	23400 of 81920 bytes (min: 23400 bytes)
max free block: 22992 bytes (min: 18368 bytes)
Board	Chip: ESP8266 (rev. 0)
Cores: 1, frequency: 80 mHz
Flash size: 4 MB (real size: 4 MB)
Last reset reason	Hardware Watchdog

Looks like the board is restarting continuously by the hardware watchdog. I could be wrong but it seems like a memory leakage. Whenever the minimum is reached the board is restarted.

**Comment by Laxilef** [comment]
Hi,
There is very little information to localize the problem.
How often do restarts happen? Can you upload logs?

**Comment by abratchik** [comment]
Hmm, I tried it on a different power source, worked more stable. Seems like not related to the code, sorry. Closing the issue
