### ISSUE TITLE
Boiler Immergas Victrix Zeus 25

### ISSUE THREAD

**Issue by VladaWaas** [Laxilef/OTGateway#92]
Actualy status:
![Snímek obrazovky 2024-11-13 102957](https://github.com/user-attachments/assets/0677c90a-9ee0-43dc-ab1e-0ceeba8f1b9b)
This is compatible points with OpenTherm:
![zeus25](https://github.com/user-attachments/assets/c2a4a69d-6acc-421b-8067-3939b0754932)
Could you add points: 19,77 and 85 to your firmware?
Thank you in adwance.
Vladimir

**Comment by Laxilef** [comment]
Hi,

ID 19 - DHW flow rate, it is already supported.
What do ID 77 & 85?

**Comment by VladaWaas** [comment]
Hello,
thx for fast respose. ID flow rate is permanently zero on interface. Can I any mistake in my setup?
ID 77 represented intake relative ventilation level 0-100%
ID 85 represented actual inlet fan speed in rpm

**Comment by Laxilef** [comment]
I will add polling ID 85 to the new version.

https://github.com/Laxilef/OTGateway/wiki#fit-coefficients

**Comment by Laxilef** [comment]
> ID19- flow rate is permanently zero on interface. Can I have any mistake in my setup?

Well, not all boilers report this parameter.

**Comment by VladaWaas** [comment]
> > ID19- flow rate is permanently zero on interface. Can I have any mistake in my setup?
> 
> Well, not all boilers report this parameter.

Immergas is not in the OpenTherm association, but its extension modules are based on OpenTherm protocols. According to a non-public information from their developer, ID 19 should be active. But it is possible that the query string may differ in some small way from the OT spec.

**Comment by VladaWaas** [comment]
> I will add polling ID 85 to the new version.

Thank you!
> 
> > I have one more question about setting the equithermal constants.
> 
> https://github.com/Laxilef/OTGateway/wiki#fit-coefficients

I reading it last week. I did exactly according to your instructions immediately after installation. But I'm a pretty impatient person. Any intervention in the system has a long inertia. I will have to improve! :))))

**Comment by Laxilef** [comment]
> Immergas is not in the OpenTherm association, but its extension modules are based on OpenTherm protocols. According to a non-public information from their developer, ID 19 should be active. But it is possible that the query string may differ in some small way from the OT spec.

Hmm, in the firmware we interpret response as float. Can you open the hot water tap and start logging?

**Comment by VladaWaas** [comment]
> > Immergas is not in the OpenTherm association, but its extension modules are based on OpenTherm protocols. According to a non-public information from their developer, ID 19 should be active. But it is possible that the query string may differ in some small way from the OT spec.
> 
> Hmm, in the firmware we interpret response as float. Can you open the hot water tap and start logging?

yes I do. Can I acces via telnet in debug mode?

**Comment by VladaWaas** [comment]
[putty.log](https://github.com/user-attachments/files/17738751/putty.log)

**Comment by Laxilef** [comment]
``ID:   19   Request: 80130000   Response: 70130000   Attempt:  1   Status: INVALID``
Your boiler responds with INVALID response to DHW flow rate request

**Comment by VladaWaas** [comment]
yes i noticed it as soon as i opened telnet. But I don't want to give up yet. I will ask the developer technician from the manufacturer if it is the same request at Imerrgas as specified by opentherm. Can you please send me the script of your command to fetch the values?

**Comment by VladaWaas** [comment]
so I don't have positive information :(
 ID19 is active only in models with direct flow heating without a hot water storage tank
